############################
# Minimal cargo-deny config
############################

[advisories]
vulnerabilities = "deny"
unmaintained   = "warn"
yanked         = "deny"
notice         = "warn"
ignore = []

[licenses]
unlicensed = "deny"
allow = [
  "MIT", "Apache-2.0", "BSD-2-Clause", "BSD-3-Clause", "ISC",
  "Unicode-DFS-2016", "MPL-2.0", "Zlib", "BSL-1.0", "CC0-1.0", "Unlicense", "OpenSSL"
]
copyleft = "warn"
confidence-threshold = 0.8

[bans]
multiple-versions = "warn"
wildcards = "allow"
deny = []
skip = []
skip-tree = []

[sources]
unknown-registry = "warn"
unknown-git      = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
