pub mod template_handler;
pub mod accounts;
pub mod banks;
pub mod transactions;
pub mod payees;
pub mod rules;
pub mod auth;
pub mod auth_handler;
pub mod family_handler;
pub mod member_handler;
pub mod invitation_handler;
pub mod audit_handler;
pub mod ledgers;
// Demo endpoints are optional
#[cfg(feature = "demo_endpoints")]
pub mod placeholder;
pub mod enhanced_profile;
pub mod currency_handler;
pub mod currency_handler_enhanced;
pub mod tag_handler;
pub mod category_handler;
