[build]
# 使用所有可用的CPU核心进行编译
jobs = 8

[profile.dev]
# 开发模式优化
opt-level = 1           # 基本优化，编译更快
debug = 1               # 减少调试信息
split-debuginfo = "unpacked"

[profile.release]
# Release模式优化
opt-level = 3           # 最大优化
lto = "thin"           # 链接时优化（thin比fat更快）
codegen-units = 1      # 单代码生成单元，优化更好
strip = true           # 移除符号信息，减小体积
panic = "abort"        # 使用abort而不是unwind，性能更好

[profile.release-fast]
# 快速Release编译（牺牲一些优化换取编译速度）
inherits = "release"
opt-level = 2          # 中等优化
lto = false           # 不进行链接时优化
codegen-units = 16    # 并行编译

# 增量编译默认已启用

# 使用默认链接器