name: jive_money
description: "Jive Money - 集腋记账 Personal Finance Management App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI 和设计
  cupertino_icons: ^1.0.6
  material_color_utilities: ^0.11.1
  
  # 状态管理
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  provider: ^6.1.1
  
  # 数据模型
  freezed_annotation: ^2.4.4
  
  # 路由导航
  go_router: ^12.1.3
  
  # 本地存储
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.3
  
  # 网络请求
  dio: ^5.4.0
  retrofit: ^4.7.2
  json_annotation: ^4.9.0
  
  # Rust 桥接
  # flutter_rust_bridge: ^2.0.0-dev.11
  
  # 工具库
  intl: ^0.20.2
  uuid: ^4.2.1
  logger: ^2.6.1
  
  # 图表和可视化
  fl_chart: ^0.66.2
  
  # 图片选择
  image_picker: ^1.0.7
  
  # 图标和字体
  flutter_svg: ^2.2.1
  # google_fonts: ^6.2.0  # 移除Google字体，使用系统字体
  
  # 平台相关
  # device_info_plus: ^9.1.1  # 暂时注释，需要 Android V2 嵌入
  # package_info_plus: ^4.2.0  # 暂时注释，需要 Android V2 嵌入
  
  # 安全和加密
  crypto: ^3.0.6
  
  # 文件处理
  path_provider: ^2.1.5
  file_picker: ^8.3.7
  
  # 图片处理
  cached_network_image: ^3.4.1
  # image_picker: ^1.0.4  # 暂时注释掉，有兼容性问题
  
  # 国际化
  flutter_localizations:
    sdk: flutter
  http: ^1.2.0
  # flutter_secure_storage: ^4.2.1  # 暂时注释，需要 Android V2 嵌入
  # connectivity_plus: ^6.0.3  # 暂时注释，需要 Android V2 嵌入

  web_socket_channel: any
  mailer: any
  share_plus: any
  screenshot: any
  uni_links: any
  qr_flutter: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # 分析器
  analyzer: ^6.2.0
  
  # 代码生成
  build_runner: ^2.4.13
  # riverpod_generator 2.6.x 需要 source_gen ^2.0.0，与 hive_generator 2.0.1 (source_gen ^1.x) 冲突
  # 回退到 2.4.x 以保持与 hive_generator 兼容
  riverpod_generator: ^2.4.0
  retrofit_generator: ^8.2.1
  # Revert json_serializable upgrade: 6.11.x pulls source_gen >=3.1.0 which
  # conflicts with hive_generator (source_gen ^1.x). Keep at 6.8.0 for now.
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  freezed: ^2.5.2
  
  # 代码质量
  flutter_lints: ^3.0.2
  very_good_analysis: ^5.1.0
  
  # 图标生成
  flutter_launcher_icons: ^0.13.1


  riverpod: any
dependency_overrides:
  # 解决flutter_localizations与intl版本冲突
  # Flutter 3.35.3的flutter_localizations需要intl 0.19.0
  intl: ^0.19.0

# Flutter 配置
flutter:
  uses-material-design: true
  
  # 资源文件
  assets:
    - assets/images/
  
  # 自定义字体（暂时注释，等字体文件准备好后启用）
  # fonts:
  #   - family: Geist
  #     fonts:
  #       - asset: assets/fonts/Geist-Regular.ttf
  #       - asset: assets/fonts/Geist-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Geist-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Geist-Bold.ttf
  #         weight: 700
  #   
  #   - family: GeistMono
  #     fonts:
  #       - asset: assets/fonts/GeistMono-Regular.ttf
  #       - asset: assets/fonts/GeistMono-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/GeistMono-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/GeistMono-Bold.ttf
  #         weight: 700

# 启动图标配置
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"
