version: '3.8'

services:
  # 开发环境的 Jive API 服务（支持热重载）
  jive-api-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: jive-api-dev
    restart: unless-stopped
    environment:
      # 数据库配置
      DATABASE_URL: postgresql://postgres:postgres@host.docker.internal:5432/jive_money
      DATABASE_MAX_CONNECTIONS: 10
      # API配置
      API_PORT: 8012
      HOST: 0.0.0.0
      RUST_LOG: debug
      RUST_BACKTRACE: 1
      # JWT配置
      JWT_SECRET: dev-secret-key-for-development-only
      JWT_EXPIRY: 86400
      # CORS配置（开发环境允许所有源）
      CORS_ORIGIN: "*"
      CORS_ALLOW_CREDENTIALS: "false"
      # 环境模式
      ENVIRONMENT: development
      # 开发模式
      CARGO_WATCH: "true"
    ports:
      - "8012:8012"
      - "9229:9229"  # 调试端口
    networks:
      - jive-network
    volumes:
      # 源码挂载（实现热重载）
      - ./src:/app/src:rw
      - ./Cargo.toml:/app/Cargo.toml:rw
      - ./Cargo.lock:/app/Cargo.lock:rw
      - ./.env:/app/.env:rw
      - ./logs:/app/logs:rw
      - ./static:/app/static:rw
      # Cargo 缓存（加速构建）
      - cargo-cache:/usr/local/cargo/registry
      - cargo-target:/app/target
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: |
      sh -c "
        cargo install cargo-watch && 
        cargo watch -x 'run --bin jive-api' -w src -w Cargo.toml
      "

volumes:
  cargo-cache:
    driver: local
  cargo-target:
    driver: local

networks:
  jive-network:
    driver: bridge